var namespace_word_quizzle =
[
    [ "Registrazione di un utente​:", "index.html#autotoc_md6", null ],
    [ "login(nickUtente, password):", "index.html#autotoc_md7", null ],
    [ "logout(nickUtente):", "index.html#autotoc_md8", null ],
    [ "aggiungi_amico (nickUtente, nickAmico):", "index.html#autotoc_md9", null ],
    [ "lista_amici(nickUtente):", "index.html#autotoc_md10", null ],
    [ "mostra_punteggio(nickUtente): ​", "index.html#autotoc_md11", null ],
    [ "mostra_classifica(nickUtente): ​", "index.html#autotoc_md12", null ],
    [ "Bot", "class_word_quizzle_1_1_bot.html", "class_word_quizzle_1_1_bot" ],
    [ "Challenge", "class_word_quizzle_1_1_challenge.html", "class_word_quizzle_1_1_challenge" ],
    [ "DataBase", "interface_word_quizzle_1_1_data_base.html", "interface_word_quizzle_1_1_data_base" ],
    [ "DataBaseJSON", "class_word_quizzle_1_1_data_base_j_s_o_n.html", "class_word_quizzle_1_1_data_base_j_s_o_n" ],
    [ "Dictionary", "interface_word_quizzle_1_1_dictionary.html", "interface_word_quizzle_1_1_dictionary" ],
    [ "DictionaryTxt", "class_word_quizzle_1_1_dictionary_txt.html", "class_word_quizzle_1_1_dictionary_txt" ],
    [ "Notifier", "class_word_quizzle_1_1_notifier.html", "class_word_quizzle_1_1_notifier" ],
    [ "Player", "class_word_quizzle_1_1_player.html", "class_word_quizzle_1_1_player" ],
    [ "Session", "class_word_quizzle_1_1_session.html", "class_word_quizzle_1_1_session" ],
    [ "Translator", "class_word_quizzle_1_1_translator.html", null ],
    [ "User", "class_word_quizzle_1_1_user.html", "class_word_quizzle_1_1_user" ],
    [ "UserRegistry", "interface_word_quizzle_1_1_user_registry.html", "interface_word_quizzle_1_1_user_registry" ],
    [ "UserRegistryService", "class_word_quizzle_1_1_user_registry_service.html", "class_word_quizzle_1_1_user_registry_service" ],
    [ "WordQuizzleClient", "class_word_quizzle_1_1_word_quizzle_client.html", "class_word_quizzle_1_1_word_quizzle_client" ],
    [ "WordQuizzleClientService", "class_word_quizzle_1_1_word_quizzle_client_service.html", "class_word_quizzle_1_1_word_quizzle_client_service" ],
    [ "WordQuizzleServer", "class_word_quizzle_1_1_word_quizzle_server.html", "class_word_quizzle_1_1_word_quizzle_server" ],
    [ "WordQuizzleServerService", "class_word_quizzle_1_1_word_quizzle_server_service.html", "class_word_quizzle_1_1_word_quizzle_server_service" ],
    [ "WordQuizzleService", "interface_word_quizzle_1_1_word_quizzle_service.html", "interface_word_quizzle_1_1_word_quizzle_service" ],
    [ "WQCli", "class_word_quizzle_1_1_w_q_cli.html", "class_word_quizzle_1_1_w_q_cli" ],
    [ "WQGui", "class_word_quizzle_1_1_w_q_gui.html", "class_word_quizzle_1_1_w_q_gui" ]
];